### ISSUE TITLE
Processing failed in resplicing

### ISSUE THREAD

**Issue by sponnusa** [daily-demos/filler-word-removal#3]
When uploaded with a small 2 minutes mp4 having a talk, it errors in FFMPEG and in resplice.

Console output:
```

Moviepy - Running:
> > > "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "/test/filler-word-removal/server/project.py", line 143, in resplice
    ffmpeg_extract_subclip(source_video_path, start, end,
  File "/test/filler-word-removal/venv/lib/python3.11/site-packages/moviepy/video/io/ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "/test/filler-word-removal/venv/lib/python3.11/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
    
    
FFMPEG Error output:

Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
[mp4 @ 0x6ebf840] Using non-standard frame rate 16/1
[mp4 @ 0x6ebf840] You requested a copy of the original timecode track so timecode metadata are now ignored
[mp4 @ 0x6ebf840] Could not find tag for codec none in stream #2, codec not currently supported in container
[out#0/mp4 @ 0x6ebf580] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!

```

And followed by the error:

```
Traceback (most recent call last):
  File "/test/filler-word-removal/server/project.py", line 96, in process
    self.resplice(source_video_path, split_times)
  File "/test/filler-word-removal/server/project.py", line 149, in resplice
    raise Exception('failed to split clips') from e
Exception: failed to split clips
failed to split clips

```

The environment is 3.11 and ffmpeg4.2.2 is installed with moviepy automatically. Also, a latest version of ffmpeg is available at /usr/loca/bin/ folder as well. All the venv and requirements are completely installed without any issues.

**Comment by bdruth** [comment]
I'm getting the same issue - did you ever sort this @sponnusa ?

**Comment by bdruth** [comment]
I was able to sort this, but the python script launches so many ffmpeg processes that it crashes. Nothing I've done seems to help it clean up the zombie sub processes, they only go away when I quit quant.

I used `ffmpeg` to strip the extra data track (timecode data in my case) - `ffmpeg -i <input-file> -c copy -write_tmcd 0 <output.mp4>`
